repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: trailing-whitespace
        language_version: python3.6
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E265,E309,E501
        language_version: python3.6
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
        args: ['--maxkb=5000']
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: flake8
        language_version: python3.6
        args:
        - --ignore=E501,E402
-   repo: git@github.com:pre-commit/pre-commit
    sha: v1.4.1
    hooks:
    -   id: validate_manifest
-   repo: git@github.com:asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
